import React from 'react';
import Preloader from '../../common/preloader/Preloader';
import s from "./ProfileInfo.module.css";
import blankUserPicture from '../../../assets/images/user.jpg'




function ProfileInfo (props){

    if (!props.userProfile){
        return(
            <Preloader/>
        )
    }


    return(
<div className={s.content}>  {/* this is the way you encapsulate css: s- means your css class is in an object, and you call your className from the object, where s - is an object (separate for each component if you named css file with the word .module.) and body is a key in an object; and value for the key body is some complicated class name automatically generated by the object   */}

<div>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Despicable_Me_logo.svg/2560px-Despicable_Me_logo.svg.png"/>
</div>

<div className={s.descriptionBlock}>{props.userProfile.aboutMe? props.userProfile.aboutMe: "nothing returned"}

    <img src= {props.userProfile.photos.large !=null ? props.userProfile.photos.large : blankUserPicture} style={{width:'300px'}} ></img>  

</div>





</div>
    )
}

export default ProfileInfo