import React from 'react';
import Preloader from '../../common/preloader/Preloader';
import s from "./ProfileInfo.module.css";
import blankUserPicture from '../../../assets/images/user.jpg'
import ProfileStatus from './ProfileStatus';
import ProfileStatusHooks from './ProfileStatusHooks';
import { useState } from 'react';
import { useEffect } from 'react';





function ProfileInfo (props){

let [isHovering, setIsHovering] = useState(false)
 let imageDomElement = React.createRef()


let removeOnMouseOut =()=>{
    console.log("remove listener")
imageDomElement.current.removeEventListener('mouseout', handleMouseOut)
} 


let handleMouseOut = ()=>{
    setTimeout(()=>{
        console.log("mouse out")
        setIsHovering(false)
    },3000)
    
}

   let handleMouseOver = ()=>{
    setIsHovering(true);
    }


  let changeUsersPhoto = (e) =>{
        if(e.target.files.length){
            props.savePhoto(e.target.files[0]);
        }
    }


    if (!props.userProfile){
        return(
            <Preloader/>
        )
    }


    return(

        <div className={s.aboutUser}>
                
        <div className={s.userImgWrapper}  onMouseOver={handleMouseOver}  onMouseOut = {handleMouseOut}   ref = {imageDomElement} >
{props.isFetching ? <Preloader/> : <img src= {props.userProfile.photos.large !=null ? props.userProfile.photos.large : blankUserPicture} ></img> }
       

        {  /* isHovering && */  props.isOwner && 
        <label className={s.photoUpload}     >
        <input className={s.inputFile} type = {"file"}   onChange={(e)=>{changeUsersPhoto(e)}}   onClick = {removeOnMouseOut}   ></input>
        </label>
        }



         </div>


        


        <div className={s.userInfo}>
        
        <div className={s.fullName} > {props.userProfile.fullName} </div>
        <div className= {s.location}> {props.userProfile.lookingForAJobDescription? props.userProfile.lookingForAJobDescription :"United States of Enchanted World"}</div>
       
        <div className={s.about}>
            <div>{props.userProfile.aboutMe}</div> 
      <div className={s.profileStatus} >  <ProfileStatusHooks status={props.status} updateStatus={props.updateStatus}/>    </div>
        </div>
        
        <ul className={s.item_social}>
        
{props.userProfile.contacts.facebook ? 
        <li className={s.facebook}> 
            <a href={`//${props.userProfile.contacts.facebook}/`} target="_blank" > <img src= "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/2021_Facebook_icon.svg/800px-2021_Facebook_icon.svg.png"/> </a>
        </li>
:null
}

{props.userProfile.contacts.instagram?
        
        <li className={s.instagram}>
            <a href={`//${props.userProfile.contacts.instagram}/`} target="_blank"> <img src="https://tbrsteakhouse.com/wp-content/uploads/2018/11/instagram-colourful-icon.png"/></a>
        </li>
:null
}

        {props.userProfile.contacts.youtube?
        <li className={s.youTube}>
            <a href={`//${props.userProfile.contacts.youtube}/`} target="_blank"><img src="https://cdn.icon-icons.com/icons2/1907/PNG/512/iconfinder-youtube-4555888_121363.png"/></a>
        </li>
: null
}

{props.userProfile.contacts.website?
        <li className={s.website} style={{width:'35px;'}}>
            <a href={`//${props.userProfile.contacts.website}/`}  target="_blank"><img src="http://cdn.onlinewebfonts.com/svg/img_504359.png"/></a>
        </li>
:null
}

      {props.userProfile.contacts.github?  
        <li className={s.github}>
            <a href={`//${props.userProfile.contacts.github}/`} target="_blank"><img src="https://cdn-icons-png.flaticon.com/512/25/25231.png"/></a>
        </li>
:null

}
        </ul>
        </div>

{props.userProfile.lookingForAJob?    
        <div className={s.isLookingForAJob}>
<div className={s.LookingForAJobImgWrapper}>
    <span>Looking for a job !</span>
</div>
    </div>
:null}

        </div>
    )
}

export default ProfileInfo













// <div className={s.content}>  {/* this is the way you encapsulate css: s- means your css class is in an object, and you call your className from the object, where s - is an object (separate for each component if you named css file with the word .module.) and body is a key in an object; and value for the key body is some complicated class name automatically generated by the object   */}

// <div>
// <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Despicable_Me_logo.svg/2560px-Despicable_Me_logo.svg.png"/>
// </div>

// <div className={s.descriptionBlock}>{props.userProfile.aboutMe? props.userProfile.aboutMe: "nothing returned"}

//     <img src= {props.userProfile.photos.large !=null ? props.userProfile.photos.large : blankUserPicture} style={{width:'300px'}} ></img>  

// </div>
